### ISSUE TITLE
Executing 'onSchedulerInitialized' on every request might be a bug

### ISSUE THREAD

**Issue by pamtbaau** [wernerjoss/grav-plugin-caldav2ics#1]
Just to let you know... See https://github.com/getgrav/grav/issues/3309

**Comment by wernerjoss** [comment]
ok, thanks for investigating more on this topic - I had no clue what could be wrong with my approach via `onSchedulerInitialized` just like the 2 other mentioned plugins do :smile: 
so, I'll keep an eye on what might be changed by the grav team here.
I will also look again into the `onAdminAfterSave` code and try to figure out if this could be triggered only when saving the plugin's configuration, and not on every Admin save request (although I don't see this as a real problem, as usually, nothing happens when no changes to the plugin or its configuration happens).
any hints on how to achieve this are welcome.
However, the best solution here would be to get rid of this whole workaround, which is just there because an external php file with `#!/usr/bin/env php` shebang is not processed correctly when called by the scheduler.
maybe I should file a bug report on this ?
